### ISSUE TITLE
NegativeArraySizeException Error when running

### ISSUE THREAD

**Issue by Bonesbhbhbh** [Bonesbhbhbh/Sorting-Competition#2]
I ran javac .\group0.java to compile (it worked but I had to run it a second time with -Xlint)

When running  java Group0 .\temp1 .\output I get the following error:
Exception in thread "main" java.lang.NegativeArraySizeException: -727379968
        at Group0.bucket(Group0.java:105)
        at Group0.sort(Group0.java:89)
        at Group0.main(Group0.java:37)

**Comment by Bonesbhbhbh** [comment]
For reference line 105 is the initialization of the round 3 array: LinkedList<int[]>[] round3 = new LinkedList[numStrings*numStrings*numStrings];

I think for some reason numStrings mught be neagtive (which is cancelled out by the +1 in round 1 and the ^2 in round 2)

**Comment by Bonesbhbhbh** [comment]
Line 37: sort(toSort)
Line 89: Arrays.sort(bucket(toSort), new SortingCompetitionComparator());

**Comment by Bonesbhbhbh** [comment]
Issue was that the size of the array was too big and it was bugging out given the constraints of integers(looping back around and becoming negative when too big). Fixed by capping the buckets to be smaller, look more into the largest an int can be
